--- #YAML:1.0
name:                Mail-ListDetector
version:             1.01
abstract:            Mailing list message detector
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Carp:                          0
    Email::Abstract:               0
    Email::Valid:                  0.12
    Test::More:                    0.08
    URI:                           1.1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Michael Stevens <michael@etla.org>
